version: '3.3'
services:
  db:
    build: .
    env_file:
      - env-postgres.env
    volumes:
      - f-pgdata-volume:/pgdata:z
      - type: bind
        source: ./db/setup.sql
        target: /pgconf/setup.sql
        consistency: cached
      - type: bind
        source: ./sql
        target: /sql
        consistency: cached
      - type: bind
        source: ./scripts
        target: /scripts
        consistency: cached
    ports:
      - '5432:5432'
volumes:
  f-pgdata-volume:
